-- Variáveis customizáveis 1–5 + protocolo gerado no envio
ALTER TABLE email_marketing_contacts
  ADD COLUMN IF NOT EXISTS var1 TEXT,
  ADD COLUMN IF NOT EXISTS var2 TEXT,
  ADD COLUMN IF NOT EXISTS var3 TEXT,
  ADD COLUMN IF NOT EXISTS var4 TEXT,
  ADD COLUMN IF NOT EXISTS var5 TEXT;

ALTER TABLE email_marketing_recipients
  ADD COLUMN IF NOT EXISTS var1 TEXT,
  ADD COLUMN IF NOT EXISTS var2 TEXT,
  ADD COLUMN IF NOT EXISTS var3 TEXT,
  ADD COLUMN IF NOT EXISTS var4 TEXT,
  ADD COLUMN IF NOT EXISTS var5 TEXT,
  ADD COLUMN IF NOT EXISTS protocol VARCHAR(20);
